# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Mac_Kubernetes_Helm
  demands: Agent.Name -equals Kunal-Jains-MacBook-Pro

stages:
- stage: terraformInit
  jobs:
  - job: initializeTerraform
    steps:
    - bash: cd terraform
    - bash: ls -ltrh
